### ISSUE TITLE
Script should not FAIL if security updates are needed to non-critical packages

### ISSUE THREAD

**Issue by jgannondo** [digitalocean/marketplace-partners#23]
@ryanpq suggested the following heuristic:

1. Is it listed here: https://usn.ubuntu.com/
2. Is it an update to one of the core packages being used for the product (such as apache if that's the  web server the product uses).

If the answer to both is no and the number of updates is minimal (less than 15 or so) then do not FAIL the image.

**Comment by ryanpq** [comment]
Closing this as multiple changes were made since this issue was opened that included further restrictions on the packages that will result in a fail.  While we cannot fully judge impact we no longer fail tests on normal package updates and only worry about security updates.  The impact of a specific update on a specific stack and configuration does require some human review and we should expect that all images when submitted are fully updated.
