### ISSUE TITLE
Cleanup script may be too aggressive with deletions of temporary files and directories

### ISSUE THREAD

**Issue by jgannondo** [digitalocean/marketplace-partners#28]
From a Vendor who reported that the script was breaking his image:

> Sure- I didn't spend a lot of time on it, but after clearing the tmp directories, passenger stopped working. This here is what caused it:
> 
`> rm -rf /tmp/* /var/tmp/*`
> 
> There was a file created by passenger in /tmp/ So I just skipped this step to get it working.

**Comment by ryanpq** [comment]
In normal operation, /tmp is emptied on each reboot.  I do not think we should modify the cleanup script for this but we may want to update the documentation.

The preferred solution would be to add a line to the build scripts to stop the passenger service once it is installed and configured and before the cleanup runs if deleting /tmp is causing passenger to throw errors.  The lack of any file in /tmp will not be an issue on a droplet booted from the image.

Should a partner have a need to prevent their build scripts from deleting the contents of /tmp it's preferable that they make the modification in their build scripts rather than our doing so in the template.

**Comment by scottcrawford03** [comment]
@jgannondo do you have steps to reproduce this? I am having a hard time knowing what to do here to repro so I can find the right fix. If not I suggest we close this and if another one opens up we should get all the details we can.
