### ISSUE TITLE
Make one recommended image build process (remove manual)

### ISSUE THREAD

**Issue by arosales** [digitalocean/marketplace-partners#38]
This issue is to request we make one recommended method to build an image. I was going to submit a PR to just remove the "manual" method but the readme (https://github.com/digitalocean/marketplace-partners/blob/master/README.md) states "some" parts in the manual process are required for the automated process. I was not sure what parts in the manual process are required for the automated process.

Thus, this issue is to suggest we move to one recommended process, anticipating that vendors  will need to make updates to their image. Therefore, we should create a pre-req section to the automated build process that includes items needed from the manual process. Then remove references to the manual process. Going forward we then only reference one build process.

**Comment by ryanpq** [comment]
I agree with removing the manual build process and having a recommended build method (my vote would be Fabric as it's the most mature method due to it's prior internal use at DO.  Providing example scripts for multiple automated build tools will allow partners who have existing uses for these tools to work with what they know best and will allow the scripts to evolve and see improved best practices as more partners make use of them.

**Comment by arosales** [comment]
We are investigating how we can improve the build process and have one recommended process for contributors to follow. Closing this ticket, and when there is a proposal for a new process I will open a PR or new issue.
